export const icons = [
  {
    url: `/static/image/favicons/light/16x16.png`,
    media: '(prefers-color-scheme: light)',
    sizes: '16x16',
    type: 'image/png',
  },
  {
    url: `/static/image/favicons/dark/16x16.png`,
    media: '(prefers-color-scheme: dark)',
    sizes: '16x16',
    type: 'image/png',
  },
  {
    url: `/static/image/favicons/light/32x32.png`,
    media: '(prefers-color-scheme: light)',
    sizes: '32x32',
    type: 'image/png',
  },
  {
    url: `/static/image/favicons/dark/32x32.png`,
    media: '(prefers-color-scheme: dark)',
    sizes: '32x32',
    type: 'image/png',
  },
  {
    url: `/static/image/favicons/light/48x48.png`,
    media: '(prefers-color-scheme: light)',
    sizes: '48x48',
    type: 'image/png',
  },
  {
    url: `/static/image/favicons/dark/48x48.png`,
    media: '(prefers-color-scheme: dark)',
    sizes: '48x48',
    type: 'image/png',
  },
  {
    url: `/static/image/favicons/light/72x72.png`,
    media: '(prefers-color-scheme: light)',
    sizes: '72x72',
    type: 'image/png',
  },
  {
    url: `/static/image/favicons/dark/72x72.png`,
    media: '(prefers-color-scheme: dark)',
    sizes: '72x72',
    type: 'image/png',
  },
  {
    url: `/static/image/favicons/light/76x76.png`,
    media: '(prefers-color-scheme: light)',
    sizes: '76x76',
    type: 'image/png',
  },
  {
    url: `/static/image/favicons/dark/76x76.png`,
    media: '(prefers-color-scheme: dark)',
    sizes: '76x76',
    type: 'image/png',
  },
  {
    url: `/static/image/favicons/light/98x98.png`,
    media: '(prefers-color-scheme: light)',
    sizes: '98x98',
    type: 'image/png',
  },
  {
    url: `/static/image/favicons/dark/98x98.png`,
    media: '(prefers-color-scheme: dark)',
    sizes: '98x98',
    type: 'image/png',
  },
  {
    url: `/static/image/favicons/light/116x116.png`,
    media: '(prefers-color-scheme: light)',
    sizes: '116x116',
    type: 'image/png',
  },
  {
    url: `/static/image/favicons/dark/116x116.png`,
    media: '(prefers-color-scheme: dark)',
    sizes: '116x116',
    type: 'image/png',
  },
  {
    url: `/static/image/favicons/light/128x128.png`,
    media: '(prefers-color-scheme: light)',
    sizes: '128x128',
    type: 'image/png',
  },
  {
    url: `/static/image/favicons/dark/128x128.png`,
    media: '(prefers-color-scheme: dark)',
    sizes: '128x128',
    type: 'image/png',
  },
  {
    url: `/static/image/favicons/light/144x144.png`,
    media: '(prefers-color-scheme: light)',
    sizes: '144x144',
    type: 'image/png',
  },
  {
    url: `/static/image/favicons/dark/144x144.png`,
    media: '(prefers-color-scheme: dark)',
    sizes: '144x144',
    type: 'image/png',
  },
  {
    url: `/static/image/favicons/light/152x152.png`,
    media: '(prefers-color-scheme: light)',
    sizes: '152x152',
    type: 'image/png',
  },
  {
    url: `/static/image/favicons/dark/152x152.png`,
    media: '(prefers-color-scheme: dark)',
    sizes: '152x152',
    type: 'image/png',
  },
];
